version: '3.8'

services:
  eavesly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      # Mount logs directory for easier debugging
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    container_name: eavesly-test

  # Optional: Add a test runner container
  tester:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      eavesly:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app/test-data
    command: ["sleep", "infinity"]
    container_name: eavesly-tester
    profiles:
      - test

networks:
  default:
    name: eavesly-network